### ISSUE TITLE
Throwing uninitialized constant PairingMatrix::CommitReader (NameError)

### ISSUE THREAD

**Issue by sumanmaity112** [ajitsing/pairing_matrix#1]
I have installed `pairing_matrix` using `gem install pairing_matrix`. As per README.md I have `pairing_matrix.yml` in the current directory. The content of `pairing_matrix.yml` is given below
```
authors_regex: ^.*\[([\w]*)(?:\/)?([\w]*)\].*$
repos:
  - /Users/sumanm/pairing

```

But when I am trying run `pairing_matrix`, it's throwing following error
```
/Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/lib/pairing_matrix/github_commit_reader.rb:8:in `<module:PairingMatrix>': uninitialized constant PairingMatrix::CommitReader (NameError)
Did you mean?  PairingMatrix::CommitCache
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/lib/pairing_matrix/github_commit_reader.rb:7:in `<top (required)>'
	from /Users/sumanm/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sumanm/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/lib/pairing_matrix.rb:2:in `glob'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/lib/pairing_matrix.rb:2:in `<top (required)>'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/bin/pairing_matrix:2:in `require_relative'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/gems/pairing_matrix-2.1/bin/pairing_matrix:2:in `<top (required)>'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/bin/pairing_matrix:23:in `load'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/bin/pairing_matrix:23:in `<main>'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sumanm/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any idea why it's throwing this?

**Comment by ajitsing** [comment]
@sumanmaity112 Thanks for reporting the issue. I will look into it ASAP.

**Comment by ajitsing** [comment]
@sumanmaity112 I am not able to reproduce the issues. Can you please mention the exact steps to reproduce it. Also which OS are you using? Thanks!

**Comment by ajitsing** [comment]
@sumanmaity112 I think I found the issue. Can you please try with pairing_matrix 2.1.1
first uninstall the existing gem using:
`gem uninstall pairing_matrix`
then install the new one. Let me know if it solves your problem or not.

**Comment by sumanmaity112** [comment]
Hi, @ajitsing Thanks for your help. Its working fine with v2.1.1
